version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: user-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10-alpine
    container_name: nats
    restart: unless-stopped

    command: ["-js", "-m", "8222", "-DV"]
    ports:
      - "8222:8222"
    volumes:
      - nats_data:/data

volumes:
  user_db_data:
  nats_data:
